export const GET_REVIEWS_DATA = 'GET_REVIEWS_DATA';
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
export const UPDATE_FILTER_VALUES = 'UPDATE_FILTER_VALUES';
export const RESET_FILTER_VALUES = 'RESET_FILTER_VALUES';
